# Generated by Django 4.2.6 on 2023-11-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_productdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productdb',
        ),
    ]
