# Generated by Django 4.2.6 on 2023-12-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='category',
            new_name='categorys',
        ),
    ]
