# Generated by Django 4.2.6 on 2023-12-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_rename_category_categorydb_categorys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='categorys',
            new_name='category',
        ),
    ]
