# Generated by Django 4.2.6 on 2023-12-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_rename_categorys_categorydb_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='category',
            new_name='categorys',
        ),
    ]
