# Generated by Django 4.2.6 on 2023-12-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_registrationdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdb',
            old_name='name',
            new_name='username',
        ),
    ]
